apiVersion: v1
kind: Service
metadata:
  name: jenkins-cicd-service
spec:
  type: NodePort
  selector:
    app: jenkins-cicd-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
